In [10]:
import pandas as pd
from scipy.interpolate import interp1d
import numpy as np

# Laden Sie den Dataframe
#df = pd.read_excel("Test_DE_Wind_DT_index.xlsx")
#df = pd.read_excel("Test_DE_PV_DT_index.xlsx")
df = pd.read_excel("Test_DE_DT_index.xlsx")

df['time'] = pd.to_datetime(df['time'])
df = df.set_index('time')

# Erstellen Sie eine Liste der Zeitpunkte
t = list(range(8760))
t = df.index.values.astype(float)

# Erstellen Sie eine Funktion zur Interpolation
#f = interp1d(t, df['CF'], kind='cubic')
f = interp1d(t, df['load'], kind='cubic')

# Erstellen Sie eine Liste der neuen Zeitpunkte, die innerhalb des Bereichs der ursprünglichen Zeitpunkte liegen
new_t = np.linspace(t[0], t[-1], 2000)

# Interpolieren Sie die Last an den neuen Zeitpunkten
interp_load = f(new_t)

# Speichern Sie die interpolierte Zeitreihe in den Dataframe
df_new = pd.DataFrame()
df_new['interp_load'] = interp_load

# Speichern Sie den verkleinerten Dataframe
df_new.to_excel("interp_DE_load_2000.xlsx", index=False)

In [37]:
import pandas as pd
from scipy.interpolate import interp1d
import numpy as np

# Laden Sie den Dataframe
df = pd.read_excel("Test_Wind_Countries_DT_index.xlsx")
df = df.apply(pd.to_numeric, errors='coerce')

df['time'] = pd.to_datetime(df['time'])
df = df.set_index('time')

# Erstellen Sie eine Liste der Zeitpunkte
t = df.index.values.astype(float)

# Erstellen Sie eine Liste der neuen Zeitpunkte, die innerhalb des Bereichs der ursprünglichen Zeitpunkte liegen
new_t = np.linspace(t[0], t[-1], 2000)

# Erstellen Sie eine leere DataFrame, um die interpolierten Werte zu speichern
df_interp = pd.DataFrame(index=pd.to_datetime(new_t),columns=df.columns)

# Schleife durch jede Spalte im ursprünglichen DataFrame und interpolieren Sie die Werte an den neuen Zeitpunkten
for col in df.columns[:]:
    # Interpolieren Sie die Werte der aktuellen Spalte an den neuen Zeitpunkten
    f = interp1d(t, df[col], kind='cubic')
    interp_vals = f(new_t)
    print(interp_vals)
    df_interp[col] = interp_vals

df_interp.to_excel("interp_Wind_Countries_load_2000.xlsx")

[0.45843023 0.50369202 0.31121506 ... 0.01462505 0.03505866 0.06047647]
[0.0888173  0.16780125 0.34891103 ... 0.45450586 0.5399631  0.64882201]
[0.12517902 0.15749926 0.1295558  ... 0.0109311  0.02009183 0.02744697]
[0.10388611 0.11541692 0.12338907 ... 0.0432688  0.06327145 0.05945965]
[0.41931298 0.29243015 0.07500583 ... 0.81264784 0.48318516 0.30032513]
[0.37280405 0.55312049 0.61155876 ... 0.43737047 0.34187508 0.25281343]
[0.5395235  0.61362406 0.62896647 ... 0.35930733 0.30410652 0.1925145 ]
[0.11087432 0.18487479 0.18187159 ... 0.76820671 0.58110601 0.4910674 ]
[0.15923809 0.21770908 0.33071787 ... 0.13366358 0.10674969 0.11045217]
[0.58258295 0.60352458 0.53839776 ... 0.21610736 0.19774292 0.21015126]
[0.5376249  0.49994678 0.33185001 ... 0.32421649 0.35762734 0.49025905]
